-- Atualiza nome completo dos sindicatos (matching por CNPJ).
-- Nao altera a coluna sigla (continua sendo o que aparece no resto do app,
-- o nome completo fica so na aba de cadastro de sindicatos).

update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, de Assistência Social, Orientação e Formação Profissional do Acre' where cnpj='04.582.300/0001-87';
update sindicatos set nome='Federação Nacional de Cultura' where cnpj='37.138.096/0001-69';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, de Assistência Social, de Orientação e Formação Profissional do Estado de Alagoas' where cnpj='10.884.443/0001-46';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional do Amazonas' where cnpj='34.593.491/0001-43';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social, Orientação e Formação Profissional dos Estados do Pará e Amapá' where cnpj='05.359.823/0001-21';
update sindicatos set nome='Sindicato dos Professores de Educação Física do Estado da Bahia' where cnpj='07.792.110/0001-82';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional da Bahia' where cnpj='15.235.021/0001-63';
update sindicatos set nome='Sindicato dos Estabelecimentos de Ensino Livre do Estado da Bahia' where cnpj='07.158.719/0001-02';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física e Trabalhadores em Academias do Ceará' where cnpj='05.895.681/0001-17';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física do Ceará' where cnpj='18.780.240/0001-11';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional do Ceará' where cnpj='07.386.824/0001-90';
update sindicatos set nome='Sindicato dos Clubes e Entidades de Prática Desportiva do Distrito Federal' where cnpj='00.395.419/0001-90';
update sindicatos set nome='Sindicato das Academias do Distrito Federal' where cnpj='14.180.212/0001-02';
update sindicatos set nome='Sindicato dos Estabelecimentos de Ensino Livre do Estado do Espírito Santo' where cnpj='04.589.764/0001-15';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, de Assistência Social, de Orientação e Formação Profissional do Espírito Santo' where cnpj='28.500.205/0001-55';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física do Estado de Goiás' where cnpj='11.507.882/0001-00';
update sindicatos set nome='Sindicato das Academias do Estado de Goiás' where cnpj='14.167.460/0001-13';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional de Goiás' where cnpj='02.898.179/0001-71';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional do Maranhão' where cnpj='69.575.637/0001-02';
update sindicatos set nome='Sindicato dos Empregados em Academias, Ginástica e Instituições Culturais de Minas Gerais' where cnpj='73.691.206/0001-89';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais do Estado de Minas Gerais' where cnpj='00.786.960/0001-29';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional do Mato Grosso do Sul' where cnpj='01.534.858/0001-07';
update sindicatos set nome='Sindicato das Entidades Culturais, Recreativas, Assistenciais e de Orientação Social do Mato Grosso do Sul' where cnpj='37.177.458/0001-20';
update sindicatos set nome='Sindicato dos Estabelecimentos de Ensino do Estado do Mato Grosso' where cnpj='02.748.755/0001-02';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física e Entidades Esportivas do Mato Grosso' where cnpj='07.752.434/0001-97';
update sindicatos set nome='Sindicato dos Trabalhadores em Estabelecimentos de Ensino Privado da Paraíba' where cnpj='09.252.040/0001-03';
update sindicatos set nome='Sindicato das Academias Desportivas e Entidades de Práticas Esportivas da Paraíba' where cnpj='06.938.758/0001-51';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional de Pernambuco' where cnpj='09.056.763/0001-29';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional do Piauí' where cnpj='04.957.606/0001-70';
update sindicatos set nome='Sindicato dos Clubes' where cnpj='02.740.267/0001-40';
update sindicatos set nome='Sindicato das Academias do Noroeste' where cnpj='07.122.938/0001-23';
update sindicatos set nome='Sindicato das Academias do Norte do Paraná' where cnpj='19.972.582/0001-04';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas e Assistência Social de Londrina' where cnpj='03.045.493/0001-74';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas e Assistência Social de Curitiba' where cnpj='75.992.466/0001-49';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física do Paraná' where cnpj='07.276.365/0001-92';
update sindicatos set nome='Sindicato dos Clubes e Entidades Esportivas do Rio de Janeiro' where cnpj='33.966.441/0001-00';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física do Rio de Janeiro' where cnpj='03.389.506/0001-22';
update sindicatos set nome='Sindicato dos Empregados em Clubes, Federações e Academias do Estado do Rio de Janeiro' where cnpj='40.163.529/0001-40';
update sindicatos set nome='Sindicato das Academias' where cnpj='07.546.139/0001-84';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional do Rio Grande do Norte' where cnpj='09.428.194/0001-03';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional de Rondônia' where cnpj='34.449.892/0001-24';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física do Rio Grande do Sul' where cnpj='10.949.209/0001-50';
update sindicatos set nome='Federação dos Sindicatos dos Empregados em Entidades Culturais, Recreativas e Assistência Social' where cnpj='05.208.719/0001-36';
update sindicatos set nome='Sindicato das Entidades Culturais, Recreativas, Assistenciais e de Orientação Social do Rio Grande do Sul' where cnpj='93.013.670/0001-23';
update sindicatos set nome='Sindicato das Academias do Estado de Santa Catarina' where cnpj='08.394.516/0001-70';
update sindicatos set nome='Sindicato dos Professores de Florianópolis' where cnpj='00.056.863/0001-80';
update sindicatos set nome='Sindicato Patronal de Academias e Entidades de Recreação de Santa Catarina' where cnpj='72.498.892/0001-03';
update sindicatos set nome='Sindicato das Academias e Atividades Esportivas da Grande Florianópolis' where cnpj='79.255.808/0001-70';
update sindicatos set nome='Sindicato dos Professores do Norte' where cnpj='95.954.400/0001-42';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional de Sergipe' where cnpj='32.742.645/0001-96';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física do Estado de São Paulo' where cnpj='05.376.877/0001-03';
update sindicatos set nome='Sindicato das Entidades de Administração do Desporto do Estado de São Paulo' where cnpj='62.654.496/0001-74';
update sindicatos set nome='Sindicato dos Estabelecimentos de Ensino, Esporte e Atividades Técnicas do Estado de São Paulo' where cnpj='61.398.905/0001-56';
update sindicatos set nome='Sindicato dos Profissionais de Educação Física do Tocantins' where cnpj='12.479.264/0001-59';
update sindicatos set nome='Sindicato dos Estabelecimentos de Ensino Livre do Tocantins' where cnpj='26.016.680/0001-25';
update sindicatos set nome='Sindicato dos Empregados em Entidades Culturais, Recreativas, Assistência Social e Formação Profissional do Tocantins' where cnpj='00.925.880/0001-07';
